name: uni
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.2
  intl: ^0.19.0
  google_mobile_ads: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/languages/translations/assets/lang/
